# Generated by Django 5.1.2 on 2024-10-19 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_student_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
