# Generated by Django 5.1.2 on 2024-10-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_remove_student_face_encoding_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='face_encoding',
            field=models.TextField(blank=True, null=True),
        ),
    ]
